INSERT INTO all_degrees (degree_name, degree_code)
SELECT DISTINCT v.degree_name, v.degree_code
FROM (
  VALUES('Bachelor of Science' ,  'BSc' ),
('Master of Arts' ,  'MA' ),
('Doctor of Philosophy' ,  'PhD' ),
('Bachelor of Arts' ,  'BA' ),
('Master of Business Administration' ,  'MBA' ),
('Bachelor of Science','BSc' ),
('Master of Arts','MA' ),
('Doctor of Philosophy','PhD' ),
('Bachelor of Arts','BA' ),
('Master of Business Administration','MBA' ),
('Advanced Diploma of Building Design','Architectural' ),
('Advanced Diploma of Building Design','Architectural' ),
('Advanced Diploma of Creative Product Development','CUA60420' ),
('Advanced Diploma of Engineering Technology','22479VIC' ),
('Advanced Diploma of Engineering Technology - Electrical','UEE62122' ),
('Advanced Diploma of Graphic Design','CUA60320' ),
('Advanced Diploma of Interior Design','MSF60122' ),
('Advanced Diploma of Interior Design','MSF60118' ),
('Advanced Diploma of Screen and Media','CUA60620' ),
('Associate Degree in Applied Technologies','AB-APPTEC' ),
('Associate Degree of Engineering','AB-ENG' ),
('Bachelor of Accounting','BA-ACCS' ),
('Bachelor of Accounting and Business Information Technology','Professional' ),
('Bachelor of Accounting/Bachelor of Applied Innovation','BB-ACCAIN' ),
('Bachelor of Animation','BA-ANI' ),
('Bachelor of Animation/Bachelor of Applied Innovation','BB-ANIAIN' ),
('Bachelor of Arts','BA-ARTS3' ),
('Bachelor of Arts','Professional' ),
('Bachelor of Arts/Bachelor of Applied Innovation','BB-ARTAIN' ),
('Bachelor of Arts/Bachelor of Business','BB-ARTBUS2' ),
('Bachelor of Arts/Bachelor of Psychological Sciences','BB-ARTPSY' ),
('Bachelor of Arts/Bachelor of Science','BB-ARTSC' ),
('Bachelor of Aviation','BA-AV' ),
('Bachelor of Aviation Management','BA-AVMGT' ),
('Bachelor of Aviation Management/Bachelor of Applied Innovation','BB-AVMAIN' ),
('Bachelor of Aviation Management/Bachelor of Business','BB-AVMBUS3' ),
('Bachelor of Aviation and Piloting','BA-AVPIL' ),
('Bachelor of Aviation and Piloting / Bachelor of Business','BB-AVPBUS' ),
('Bachelor of Aviation/Bachelor of Business','BB-AVBUS3' ),
('Bachelor of Biomedical Science','BA-BIOMSC' ),
('Bachelor of Business','BA-BUS11' ),
('Bachelor of Business','BA-BUS11S' ),
('Bachelor of Business','BA-BUS10S' ),
('Bachelor of Business','Professional' ),
('Bachelor of Business Analytics and Analysis','BA-BAA' ),
('Bachelor of Business Analytics and Analysis/Bachelor of Applied Innovation','BB-BAAAIN' ),
('Bachelor of Business Analytics and Analysis/Bachelor of Business','BB-BAABUS1' ),
('Bachelor of Business Analytics and Analysis/Bachelor of Cyber Security','BB-BAACYB' ),
('Bachelor of Business Information Technology','Professional' ),
('Bachelor of Business/Bachelor of Applied Innovation','BB-BUSAIN1' ),
('Bachelor of Circus Arts','BA-CIRCA1' ),
('Bachelor of Computer Science','BA-CS' ),
('Bachelor of Computer Science','Honours' ),
('Bachelor of Computer Science','Professional' ),
('Bachelor of Computer Science/Bachelor of Applied Innovation','BB-CSAIN' ),
('Bachelor of Criminal Justice and Criminology','BA-CRIJUSS' ),
('Bachelor of Criminal Justice and Criminology/Bachelor of Applied Innovation','BB-CJCAIN' ),
('Bachelor of Criminal Justice and Criminology/Bachelor of Cyber Security','BB-CJCCYB' ),
('Bachelor of Cyber Security','BA-CYB' ),
('Bachelor of Data Science','BA-DS' ),
('Bachelor of Design','BA-DESS' ),
('Bachelor of Design','Architecture' ),
('Bachelor of Design','Communication Design' ),
('Bachelor of Design','Fashion' ),
('Bachelor of Design','Industrial Design' ),
('Bachelor of Design','Interior Architecture' ),
('Bachelor of Design/Bachelor of Applied Innovation','BB-DESAIN' ),
('Bachelor of Design/Bachelor of Business','BB-DESBUS1' ),
('Bachelor of Design/Bachelor of Media and Communication','BB-DESMCMN' ),
('Bachelor of Digital Construction Management','BA-DCM' ),
('Bachelor of Education','Early Childhood Teaching' ),
('Bachelor of Education','Early Childhood Teaching' ),
('Bachelor of Education','Early Childhood and Primary' ),
('Bachelor of Education','Primary' ),
('Bachelor of Education Studies','BA-EDUST' ),
('Bachelor of Engineering','Civil and Infrastructure' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering','Honours' ),
('Bachelor of Engineering Technology','BA-ENGTEC' ),
('Bachelor of Exercise and Sport Science','BA-ESS' ),
('Bachelor of Film and Television','Honours' ),
('Bachelor of Games and Interactivity','BA-GAMIA' ),
('Bachelor of Games and Interactivity/Bachelor of Animation','BB-GAMIANI' ),
('Bachelor of Games and Interactivity/Bachelor of Applied Innovation','BB-GAMAIN' ),
('Bachelor of Games and Interactivity/Bachelor of Computer Science','BB-GAMCS' ),
('Bachelor of Health Science','BA-HSC1' ),
('Bachelor of Health Science','Honours' ),
('Bachelor of Health Science','Professional' ),
('Bachelor of Health Science/Bachelor of Applied Innovation','BB-HSCAIN' ),
('Bachelor of Health Science/Bachelor of Arts','BB-HSCART' ),
('Bachelor of Health Science/Bachelor of Business','BB-HSCBUS1' ),
('Bachelor of Health Science/Bachelor of Media and Communication','BB-HSCMCMN' ),
('Bachelor of Health Science/Bachelor of Science','BB-HSCSCI' ),
('Bachelor of Information and Communication Technology','BA-ICT' ),
('Bachelor of Information and Communication Technology','BA-ICTS' ),
('Bachelor of Information and Communication Technology','Professional' ),
('Bachelor of Information and Communication Technology/Bachelor of Applied Innovation','BB-ICTAIN' ),
('Bachelor of Laws','BA-LAW' ),
('Bachelor of Laws','BA-LAWS' ),
('Bachelor of Laws - Graduate Entry','BA-LAW1S' ),
('Bachelor of Laws/Bachelor of Arts','BB-LAWART' ),
('Bachelor of Laws/Bachelor of Business','BB-LAWBUS1' ),
('Bachelor of Laws/Bachelor of Business Analytics and Analysis','BB-LAWBAA' ),
('Bachelor of Laws/Bachelor of Computer Science','BB-LAWCS' ),
('Bachelor of Laws/Bachelor of Criminal Justice and Criminology','BB-LAWCRJ' ),
('Bachelor of Laws/Bachelor of Cyber Security','BB-LAWCYB' ),
('Bachelor of Laws/Bachelor of Engineering','Honours' ),
('Bachelor of Laws/Bachelor of Media and Communication','BB-LAWMCM' ),
('Bachelor of Laws/Bachelor of Psychological Sciences','BB-LAWPSY' ),
('Bachelor of Laws/Bachelor of Science','BB-LAWSC' ),
('Bachelor of Media and Communication','BA-MCMNS' ),
('Bachelor of Media and Communication','Professional' ),
('Bachelor of Media and Communication/Bachelor of Applied Innovation','BB-MCMAIN' ),
('Bachelor of Media and Communication/Bachelor of Business','BB-MCMNBUS1' ),
('Bachelor of Nursing','BA-NUR' ),
('Bachelor of Nutrition','BA-NTR' ),
('Bachelor of Psychological Sciences','BA-PSY' ),
('Bachelor of Psychological Sciences','BA-PSYS' ),
('Bachelor of Psychological Sciences','Honours' ),
('Bachelor of Psychological Sciences/Bachelor of Applied Innovation','BB-PSYAIN' ),
('Bachelor of Psychological Sciences/Bachelor of Criminal Justice and Criminology','BB-PSYCJC' ),
('Bachelor of Science','BA-SC2' ),
('Bachelor of Science','Honours' ),
('Bachelor of Science','Professional' ),
('Bachelor of Science/Bachelor of Applied Innovation','BB-SC2AIN' ),
('Bachelor of Screen Production','BA-SCRPRD1' ),
('Bachelor of Screen Production/Bachelor of Applied Innovation','BB-SPDAIN' ),
('Bachelor of Social Science','BA-SSS' ),
('Breakthrough Lab','DFM-IAAS' ),
('Business Analysis','AGBAIS' ),
('Business Writing Skills','BUSSIS' ),
('Certificate I in EAL','Access' ),
('Certificate I in EAL','Access' ),
('Certificate I in General Education for Adults','22472VIC' ),
('Certificate I in General Education for Adults','Introductory' ),
('Certificate II in Building and Construction Pre-apprenticeship','22614VIC' ),
('Certificate II in Building and Construction Pre-apprenticeship – Bricklaying','22338VIC' ),
('Certificate II in EAL','Access' ),
('Certificate II in EAL','Access' ),
('Certificate II in Electrotechnology','Career Start' ),
('Certificate II in General Education for Adults','22473VIC' ),
('Certificate II in Plumbing','Pre-apprenticeship' ),
('Certificate III in Bricklaying and Blocklaying','CPC33020' ),
('Certificate III in Carpentry','CPC30220' ),
('Certificate III in EAL','Access' ),
('Certificate III in EAL','Access' ),
('Certificate III in Early Childhood Education and Care','CHC30121' ),
('Certificate III in Electrotechnology Electrician','UEE30820' ),
('Certificate III in Engineering - Fabrication Trade','MEM31922' ),
('Certificate III in Engineering - Fabrication Trade','MEM30319' ),
('Certificate III in Engineering - Mechanical Trade','MEM30219' ),
('Certificate III in General Education for Adults','22474VIC' ),
('Certificate III in Health Services Assistance','HLT33115' ),
('Certificate III in Individual Support','CHC33021' ),
('Certificate III in Individual Support','Ageing' ),
('Certificate III in Information Technology','ICT30120' ),
('Certificate III in Information, Digital Media and Technology','ICT30118' ),
('Certificate III in Laboratory Skills','MSL30118' ),
('Certificate III in Non-Emergency Patient Transport','HLT31120' ),
('Certificate III in Plumbing','CPC32420' ),
('Certificate IV in Accounting and Bookkeeping','FNS40222' ),
('Certificate IV in Allied Health Assistance','HLT43021' ),
('Certificate IV in Allied Health Assistance','HLT43015' ),
('Certificate IV in Building and Construction','CPC40120' ),
('Certificate IV in Circus Arts','10824NAT' ),
('Certificate IV in Community Services','CHC42021' ),
('Certificate IV in Cyber Security','22603VIC' ),
('Certificate IV in Design','CUA40720' ),
('Certificate IV in Disability Support','CHC43121' ),
('Certificate IV in Engineering','MEM40119' ),
('Certificate IV in Entrepreneurship and New Business','BSB40320' ),
('Certificate IV in Information Technology','Gaming Development' ),
('Certificate IV in Laboratory Techniques','MSL40122' ),
('Certificate IV in Leadership and Management','BSB40520' ),
('Certificate IV in Leisure and Health','CHC43415' ),
('Certificate IV in Mental Health','CHC43315' ),
('Certificate IV in Mental Health Peer Work','CHC43515' ),
('Certificate IV in Photography and Digital Imaging','CUA41120' ),
('Certificate IV in Plumbing and Services','CPC40920' ),
('Certificate IV in Professional Writing and Editing','CUA40118' ),
('Certificate IV in Project Management Practice','BSB40920' ),
('Certificate IV in School Based Education Support','CHC40221' ),
('Certificate IV in Science','22608VIC' ),
('selectedCertificate IV in Screen Media','Online delivery' ),
('Certificate IV in Training and Assessment','TAE40122' ),
('Certificate IV in Training and Assessment','TAE40116' ),
('Certificate IV in Work Health and Safety','BSB41419' ),
('Certificate IV in Youth Work','CHC40413' ),
('Certificate IV in Youth Work','CHC40421' ),
('Commercialisation Skills for Health, Medical and Medtech Researchers','MEDTECH' ),
('Confident communication – Improving your confidence and assertiveness','CCOMIS' ),
('Conflict Resolution','CONFIS' ),
('Continuing Professional Development','CPD' ),
('Contract Management Essentials','CMESIS' ),
('Course in EAL','22483VIC' ),
('Course in EAL','22637VIC' ),
('Course in Identifying and Responding to Family Violence Risk','22510VIC' ),
('Course in Initial EAL','22482VIC' ),
('Course in Initial EAL','22636VIC' ),
('Course in Introduction to the National Disability Insurance Scheme','22469VIC' ),
('Critical Thinking and Problem Solving for Local Government','CRITTIS' ),
('De-mystifying Industry 4.0 / Digital Manufacturing','SH-DMIDM' ),
('Design Thinking for Organisational Innovation','DFM-DTOI' ),
('Diploma of Accounting','FNS50222' ),
('Diploma of Accounting and Finance','DP-ACCFIN' ),
('Diploma of Applied Technologies','DP-APPTEC' ),
('Diploma of Arts and Communication','UniLink' ),
('Diploma of Building and Construction','Building' ),
('Diploma of Business','BSB50120' ),
('Diploma of Business','UniLink' ),
('Diploma of Community Services','CHC52015' ),
('Diploma of Community Services','CHC52021' ),
('Diploma of Design','UniLink' ),
('Diploma of Digital Marketing','10931NAT' ),
('Diploma of Early Childhood Education and Care','CHC50121' ),
('Diploma of Emergency Health Care','HLT51020' ),
('Diploma of Engineering','UniLink' ),
('Diploma of Engineering Technology','22478VIC' ),
('Diploma of Event Management','SIT50322' ),
('Diploma of Graphic Design','CUA50720' ),
('Diploma of Health Science','UniLink' ),
('Diploma of Human Resource Management','BSB50320' ),
('Diploma of Information Technology','ICT50220' ),
('Diploma of Information Technology','UniLink' ),
('Diploma of Interior Design','MSF50222' ),
('Diploma of Justice','22594VIC' ),
('Diploma of Laboratory Technology','MSL50118' ),
('Diploma of Laboratory Technology','MSL50122' ),
('Diploma of Leadership and Management','BSB50420' ),
('Diploma of Library and Information Services','BSB50520' ),
('Diploma of Nursing','HLT54121' ),
('Diploma of Photography and Digital Imaging','CUA50920' ),
('Diploma of Professional Writing and Editing','CUA50118' ),
('Diploma of Project Management','BSB50820' ),
('Diploma of Quality Auditing','BSB50920' ),
('Diploma of Science','UniLink' ),
('Diploma of Screen and Media','CUA51020' ),
('Diploma of Social Media Marketing','10904NAT' ),
('Diploma of Sport','SIS50321' ),
('Diploma of Sport/Diploma of Leadership and Management','SIS50321/BSB50420' ),
('Diploma of Teacher Education Preparation','22602VIC' ),
('Diploma of Visual Arts','CUA51120' ),
('Diploma of Vocational Education and Training/Diploma of Training Design and Development','TAE50116/T' ),
('Diploma of Work Health and Safety','BSB51319' ),
('Diploma of Youth Work','CHC50421' ),
('Doctor of Philosophy','DR-INTDES' ),
('Doctor of Philosophy','DR-IS' ),
('Doctor of Philosophy','DR-BUS' ),
('Doctor of Philosophy','DR-HAS' ),
('Doctor of Philosophy','DR-DES' ),
('Doctor of Philosophy','DR-INTHTHS' ),
('Doctor of Philosophy','DR-HTHSCI' ),
('Doctor of Philosophy','DR-INTHAS' ),
('Doctor of Philosophy','DR-TECFBL' ),
('Doctor of Philosophy','DR-LAW' ),
('Doctor of Philosophy','DR-SCI' ),
('Doctor of Philosophy','DR-INTBUS' ),
('Doctor of Philosophy','DR-TECHAD' ),
('Doctor of Philosophy','DR-INTICT' ),
('Doctor of Philosophy','DR-ICT' ),
('Doctor of Philosophy','DR-ENG' ),
('Doctor of Philosophy','DR-INTSCI' ),
('Doctor of Philosophy','DR-BUSPRC' ),
('Doctor of Philosophy','DR-TECHIN' ),
('Doctor of Philosophy','Clinical Psychology' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-ENGGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-ICTGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-LAWGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-DESGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-HTHGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-HASGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-BUSGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-ISGC' ),
('Doctor of Philosophy and Graduate Certificate of Research and Innovation Management','DR-SCIGC' ),
('Doctor of Psychology','Clinical and Forensic Psychology' ),
('Emotional Intelligence Training','BLEIIS' ),
('Empowering Women in the Workplace','WINFIS' ),
('English Language Intensive Course for Overseas Students','ELICOS' ),
('Enterprise Trainer - Presenting Skill Set','TAESS00014' ),
('Executive Coaching Program','SS-COACH1' ),
('Finance for Non-Finance Managers - Understanding Numbers and Business Impact','FFFMIS' ),
('Generative AI for professionals: Your productivity partner','GENAI' ),
('Graduate Certificate in Applied Business','10840NAT' ),
('Graduate Certificate in Client Assessment and Case Management','CHC82015' ),
('Graduate Certificate in Clinical Supervision','GC-CLSUP' ),
('Graduate Certificate in Construction Management','GC-CMGT' ),
('Graduate Certificate in Forensic Behavioural Science','GC-FBS' ),
('Graduate Certificate in Forensic Mental Health Nursing','GC-FMHN' ),
('Graduate Certificate in Learning and Teaching','Higher Education' ),
('Graduate Certificate in Organisational Coaching','11252NAT' ),
('Graduate Certificate in Organisational Coaching','10778NAT' ),
('Graduate Certificate of Applied Statistics','GC-APPS' ),
('Graduate Certificate of Aviation','GC-AV' ),
('Graduate Certificate of Aviation','Piloting' ),
('Graduate Certificate of Business Administration','GC-BUSADM4' ),
('Graduate Certificate of Business Administration','GC-BUSADM2S' ),
('Graduate Certificate of Business Administration','Executive' ),
('Graduate Certificate of Business Information Systems','GC-BIS1' ),
('Graduate Certificate of Counselling','GC-COU' ),
('Graduate Certificate of Cyber Security','GC-CYBSEC' ),
('Graduate Certificate of Cyber Security Management','GC-CYMGTS' ),
('Graduate Certificate of Data Science','GC-DATASC' ),
('Graduate Certificate of Design','GC-DESG' ),
('Graduate Certificate of Educational Studies','GC-EDUSTU1' ),
('Graduate Certificate of Engineering','GC-ENG' ),
('Graduate Certificate of Entrepreneurship','GC-ENT' ),
('Graduate Certificate of Entrepreneurship and Innovation','GC-ENTINN3' ),
('Graduate Certificate of Financial Planning','GC-FINPLS' ),
('Graduate Certificate of Financial Technologies','GC-FINTEC' ),
('Graduate Certificate of Forensic Psychiatric Practice','GC-FPP' ),
('Graduate Certificate of Human Resource Management','GC-HRM' ),
('Graduate Certificate of Information Technology','GC-IT1' ),
('Graduate Certificate of Management','GC-MGTS' ),
('Graduate Certificate of Management','Workplace Transformation' ),
('Graduate Certificate of Marketing','GC-MKT' ),
('Graduate Certificate of Media and Communication','GC-MCO' ),
('Graduate Certificate of Product Management','GC-PROMS' ),
('Graduate Certificate of Professional Accounting','GC-PACC' ),
('Graduate Certificate of Professional Data Analytics','GC-PAS' ),
('Graduate Certificate of Programming and Development','GC-PDS' ),
('Graduate Certificate of Project Management','GC-PMS' ),
('Graduate Certificate of Psychology','GC-PSYS' ),
('Graduate Certificate of Research and Innovation Management','GC-RESIM' ),
('Graduate Certificate of Science','Astronomy' ),
('Graduate Certificate of Social Impact','GC-SI' ),
('Graduate Certificate of Supply Chain Innovation','GC-SCI' ),
('Graduate Certificate of Urban Design','GC-UD' ),
('Graduate Certificate of Urban Informatics','GC-UI' ),
('Graduate Certificate of Writing','GC-WRI' ),
('Graduate Diploma in Applied Statistics','GD-APPS' ),
('Graduate Diploma in Clinical Supervision','GD-CLSUP' ),
('Graduate Diploma in Forensic Psychology','GD-PSYFOR' ),
('Graduate Diploma of Aviation','GD-AV' ),
('Graduate Diploma of Counselling','GD-COU' ),
('Graduate Diploma of Cyber Security','GD-CYBSEC' ),
('Graduate Diploma of Early Childhood Teaching','GD-ECTEA' ),
('Graduate Diploma of Early Childhood Teaching','GD-ECTEAS' ),
('Graduate Diploma of Entrepreneurship','GD-ENT' ),
('Graduate Diploma of Environmental Health Practice','GD-ENVHP' ),
('Graduate Diploma of Financial Planning','GD-FINPLS' ),
('Graduate Diploma of Forensic Behavioural Science','GD-FBS' ),
('Graduate Diploma of Forensic Mental Health Nursing','GD-FMHN' ),
('Graduate Diploma of Information Technology','GD-IT1' ),
('Graduate Diploma of Professional Accounting','GD-PACC' ),
('Graduate Diploma of Project Management','GD-PMS' ),
('Graduate Diploma of Psychology','GD-PSYS' ),
('Graduate Diploma of Psychology','Advanced' ),
('Graduate Diploma of Science','Astronomy' ),
('Graduate Diploma of Science','Biotechnology' ),
('Graduate Diploma of Writing','GD-WRI' ),
('How to have a difficult conversation','DIFFCIS' ),
('Hydrogen fundamentals – An emerging frontier in the energy landscape','HYDROFUN' ),
('Industrial Training Course: PSS®E Module 1','SH-PSSEM01' ),
('Industrial Training Course: PSS®E Module 2','SH-PSSEM02' ),
('Industrial Training Course: PSS®SINCAL Module 1','SH-PSSSIN1' ),
('Innovation Huddle','DFM-FTSP' ),
('International Exchange Program','IX-INTX' ),
('International Exchange Program','12 Months' ),
('International Study Abroad Program','SA-INTSA' ),
('International Study Abroad Program','12 Months' ),
('Introduction to Welding','WELTD70W' ),
('Lead Auditor Training','SS-AUDIT1' ),
('Leadership Development Program','DEVLIS' ),
('Leading in a Hybrid Environment','LEADHYBRD' ),
('Managing for Maximum Performance','MMXPIS' ),
('Master of Architecture','MA-ARC' ),
('Master of Architecture and Urban Design','MA-ARCUD' ),
('Master of Arts','Research' ),
('Master of Aviation','MA-AV' ),
('Master of Business','Research' ),
('Master of Business Administration','MA-BUSADM5' ),
('Master of Business Administration','MA-BUSADM3S' ),
('Master of Business Administration','Executive' ),
('Master of Business Information Systems','MA-BIS' ),
('Master of Construction Management Practice','MA-CMGTP' ),
('Master of Construction and Infrastructure Management','MA-CIMGT' ),
('Master of Counselling','MA-COU' ),
('Master of Counselling','Advanced' ),
('Master of Cyber Security','MA-CYBSEC' ),
('Master of Cyber Security Management','MA-CYMGTS' ),
('Master of Data Science','MA-DATASC' ),
('Master of Design','MA-DESG' ),
('Master of Design','Research' ),
('Master of Dietetics','MA-DIET' ),
('Master of Engineering','Research' ),
('Master of Engineering Practice','MA-ENGPRC' ),
('Master of Engineering Practice/ Master of Construction Management Practice','MM-EPRCMP' ),
('Master of Engineering Science','MA-ENGSC' ),
('Master of Entrepreneurship and Innovation','MA-ENTINN5' ),
('Master of Finance','MA-FIN' ),
('Master of Forensic Behavioural Science','MA-FBS' ),
('Master of Health Sciences','Research' ),
('Master of Human Resource Management','MA-HRM1' ),
('Master of Information Technology','MA-IT1' ),
('Master of Information Technology','Professional Computing' ),
('Master of Information and Communication Technologies','Research' ),
('Master of Law','Research' ),
('Master of Marketing','MA-MKT1' ),
('Master of Media and Communication','MA-MCO' ),
('Master of Occupational Therapy','MA-OCC' ),
('Master of Physiotherapy','MA-PHYS' ),
('Master of Physiotherapy','MA-PHYS1' ),
('Master of Professional Accounting','MA-PACC' ),
('Master of Professional Accounting','MA-PACC1' ),
('Master of Professional Accounting','Extended' ),
('Master of Professional Engineering','MA-EPRE' ),
('Master of Project Management','MA-PM1' ),
('Master of Psychology','Clinical Psychology' ),
('Master of Research','MR-INTICT' ),
('Master of Research','MR-INTSCI' ),
('Master of Research','MR-INTHAS' ),
('Master of Research','MR-INTHTHS' ),
('Master of Research','MR-INTBUS' ),
('Master of Research','MR-INTDES' ),
('Master of Science','Astronomy' ),
('Master of Science','Biotechnology' ),
('Master of Science','Network Systems' ),
('Master of Science','Research' ),
('Master of Social Impact','MA-SI' ),
('Master of Supply Chain Innovation','MA-SCI1' ),
('Master of Teaching','Primary' ),
('Master of Teaching','Secondary' ),
('Master of Urban Design','MA-UD' ),
('Master of Writing','MA-WRI' ),
('Masterclass: Agile Project Management','MCAPM' ),
('Masterclass: Change Management','MCBCM' ),
('Masterclass: Design Business Strategy','MCBBS' ),
('Masterclass: Lead Innovative Thinking and Practice','MCLIT' ),
('Masterclass: Leader as Coach','MCLAC' ),
('Masterclass: The Art of Workplace Storytelling','WPSTTIS' ),
('Masterclass: Transformational Leadership','MCTLEAD' ),
('Mastering the Art of Workplace Storytelling - Online','WPSTTIS-O' ),
('Maths Link General','NN-MLFTH' ),
('Maths Link Methods','NN-MLMTH' ),
('MathsLink: General','NN-MLGEN' ),
('Mediation Training','MEFUIS' ),
('Mental Health Essentials for People Leaders','SCMHEPL' ),
('Mental Health First Aid Short Course','NC-HEAS01' ),
('Mental Health Fundamentals','SCMHF' ),
('Microsoft Excel Advanced','EXCCIS' ),
('Microsoft Excel Intermediate','EXCBIS' ),
('Microsoft Excel Introduction','EXCAIS' ),
('Microsoft Outlook','SC-MO' ),
('Microsoft Word Advanced','SC-MWA' ),
('Microsoft Word Intermediate','SC-MWI' ),
('Negotiation skills','NGOIS' ),
('New Supervisor','NEWSIS' ),
('Plumbing Licence for Common Units Skill Set','PLUMLICSS1' ),
('Positive Leadership','POLDIS' ),
('Postgraduate Qualifying Program','NN-PQP' ),
('Principles of Design Thinking','DFM-PRDSTH' ),
('Project Management Fundamentals','PRMEIS' ),
('Psychosocial Recovery Coach Short Course','NC-HEAS02' ),
('Resilience, stress management and mindfulness','RSMIS' ),
('Robotics Play and STEM for Teachers','NC-STEM01' ),
('Stress Aware and Self Care','SCSASC' ),
('Swinburne Foundation Program','SF-SFP' ),
('Undergraduate Certificate of Business','CU-BUSS' ),
('Undergraduate Certificate of Criminal Justice and Criminology','CU-CRIJUSS' ),
('UniLink Bridging Program','TE-UBP1' ),
('Victorian Certificate of Education','VCE0000001' ),
('Work Skill Instructor Skill Set','TAESS00028' ),
('Writing for the Board – Report writing for strategic influence','BOARDWR' )
) AS v(degree_name, degree_code)
ON CONFLICT (degree_name, degree_code) DO NOTHING;