// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwinStudy.Api.Data;

#nullable disable

namespace SwinStudy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228143015_AddSurveyToUsers")]
    partial class AddSurveyToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwinStudy.Api.Models.AllFlashcard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_allflashcards_pkey");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("m_allflashcards", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.Degree", b =>
                {
                    b.Property<long>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("degree_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DegreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DegreeCode")
                        .HasColumnType("text")
                        .HasColumnName("degree_code");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degree_name");

                    b.HasKey("DegreeId");

                    b.ToTable("all_degrees", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.Unit", b =>
                {
                    b.Property<long>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UnitId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_points");

                    b.Property<string>("UnitCode")
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_name");

                    b.HasKey("UnitId");

                    b.ToTable("all_units", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Degree")
                        .HasColumnType("text")
                        .HasColumnName("degree");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasSubmittedSurvey")
                        .HasColumnType("boolean")
                        .HasColumnName("has_submitted_survey");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("Semester")
                        .HasColumnType("integer")
                        .HasColumnName("semester");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.UserGeneratedFlashcard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_usergeneratedflashcards_pkey");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("QnaReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("qnareference");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("QnaReferenceId");

                    b.ToTable("m_usergeneratedflashcards", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.UserSavedFlashcard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_usersavedflashcards_pkey");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("m_usersavedflashcards", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.UserUnit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.HasKey("UserId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("user_units", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.UserGeneratedFlashcard", b =>
                {
                    b.HasOne("SwinStudy.Api.Models.AllFlashcard", "Flashcard")
                        .WithMany("GeneratedByUsers")
                        .HasForeignKey("QnaReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_m_usergeneratedflashcards_qnaref");

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("SwinStudy.Api.Models.UserUnit", b =>
                {
                    b.HasOne("SwinStudy.Api.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwinStudy.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwinStudy.Api.Models.AllFlashcard", b =>
                {
                    b.Navigation("GeneratedByUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
