// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwinStudy.Api.Data;

#nullable disable

namespace SwinStudy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwinStudy.Api.Models.Degree", b =>
                {
                    b.Property<long>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("degree_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DegreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DegreeCode")
                        .HasColumnType("text")
                        .HasColumnName("degree_code");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degree_name");

                    b.HasKey("DegreeId");

                    b.ToTable("all_degrees", (string)null);
                });

            modelBuilder.Entity("SwinStudy.Api.Models.Unit", b =>
                {
                    b.Property<long>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UnitId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_points");

                    b.Property<string>("UnitCode")
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_name");

                    b.HasKey("UnitId");

                    b.ToTable("all_units", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
